Repository cockpit-project/cockpit-machines, pull requests merged in 2021-04, with the labels that each got.

#81 workflows: Use cockpituous instead of github token for npm/po updates
  .github/workflows/npm-update.yml
  .github/workflows/po-refresh.yml
Labels: no-test

#84 Rework pre-built dist upload/download
  .github/workflows/build-dist.yml
  .github/workflows/prune-dist.yml
  .github/workflows/publish-dist.yml
  test/download-dist
Labels: blocked

#83 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#98 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#101 [no-test] Update translations from Fedora Weblate
  po/fi.po
  po/ko.po
  po/nl.po
  po/sk.po
Labels: bot, no-test, release-blocker

#102 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#109 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#110 packit: Enable tests on Rawhide, investigate TestMachinesNICs.testNICAdd regression
  packit.yaml
Labels: no-test

#115 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#117 [no-test] Update translations from Fedora Weblate
  po/ko.po
Labels: bot, no-test, release-blocker

#118 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#123 package.json: Update @patternfly/react-console, @patternfly/patternfly, @patternfly/react-table, @patternfly/react-styles, @patternfly/react-core
  package.json
Labels: bot

#116 Edit vNIC MAC address
  src/actions/provider-actions.js
  src/components/vm/nics/nicEdit.jsx
  src/libvirt-dbus.js
  src/libvirt-xml-update.js
  test/check-machines-nics
Labels: release-note

#126 workflows: Run npm-update twice a week only
  .github/workflows/npm-update.yml
Labels: no-test

#133 package.json: Update @patternfly/react-core, @patternfly/react-table, @patternfly/react-styles, @patternfly/patternfly
  package.json
Labels: bot

#136 Fix missing borders in PF4 selects
  webpack.config.js
Labels: release-blocker

#138 [no-test] Update translations from Fedora Weblate
  po/de.po
  po/ko.po
Labels: bot, no-test, release-blocker

#130 test: Adjust special cases for Ubuntu 21.04
  test/check-machines-create
  test/check-machines-lifecycle
  test/check-machines-snapshots
  test/machineslib.py
  test/vm.install
Labels: blocked

#140 package.json: Update redux
  package.json
Labels: bot
