Repository cockpit-project/cockpit-machines, pull requests merged in 2021-08, with the labels that each got.

#301 package.json: Update @patternfly/react-core, @patternfly/react-console
  package.json
Labels: bot

#306 package.json: Update redux
  package.json
Labels: bot

#312 package.json: Update @patternfly/react-console, @patternfly/react-core, @patternfly/patternfly, @patternfly/react-styles, @patternfly/react-table
  package.json
Labels: bot

#314 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#321 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#323 Fix label for removing shared directories
  src/components/vm/filesystems/vmFilesystemsCard.jsx
  test/check-machines-filesystems
Labels: release-blocker

#324 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#328 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#330 [no-test] Update translations from Fedora Weblate
  po/sv.po
Labels: bot, no-test, release-blocker

#332 package.json: Update @patternfly/react-console
  package.json
Labels: bot
