Repository cockpit-project/cockpit-machines, pull requests merged in 2021-06, with the labels that each got.

#184 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#189 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#187 [no-test] Update translations from Fedora Weblate
  po/fi.po
  po/ru.po
Labels: bot, no-test, release-blocker

#196 [no-test] Update translations from Fedora Weblate
  po/es.po
Labels: bot, no-test, release-blocker

#200 package.json: Update @patternfly/react-styles, @patternfly/react-table, @patternfly/patternfly, @patternfly/react-core
  package.json
Labels: bot

#203 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#142 Add support for configuring/viewing shared directories between VMs and host
  src/components/vm/filesystems/vmFilesystemsCard.jsx
  src/components/vm/filesystems/vmFilesystemsCard.scss
  src/components/vm/vmDetailsPage.jsx
  src/components/vm/vmDetailsPage.scss
  src/libvirt-common.js
  src/libvirt-dbus.js
  src/xmlCreator.js
  test/check-machines-filesystems
Labels: release-note

#205 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#209 Fix string in 'Share host directory' dialog
  src/components/vm/filesystems/vmFilesystemsCard.jsx
Labels: release-blocker

#207 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#210 Fix reducers updating interfaces and node devices
  src/reducers.js
  test/check-machines-lifecycle
Labels: release-blocker

#215 [no-test] Update translations from Fedora Weblate
  po/zh_CN.po
Labels: bot, no-test, release-blocker

#217 package.json: Update @patternfly/react-styles, @patternfly/patternfly, @patternfly/react-core, @patternfly/react-table, @patternfly/react-console
  package.json
Labels: bot

#218 tests: make sure package.json is ignored when installing test deps
  test/browser/run-test.sh
Labels: no-test
