Repository cockpit-project/cockpit-machines, pull requests merged in 2021-07, with the labels that each got.

#232 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#241 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#245 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#250 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#251 [no-test] Update translations from Fedora Weblate
  po/ko.po
Labels: bot, no-test, release-blocker

#254 package.json: Update @patternfly/react-console, @patternfly/react-core
  package.json
Labels: bot

#261 package.json: Update @patternfly/react-console, @patternfly/react-core
  package.json
Labels: bot

#258 Fix "current snapshot" icon
  src/components/vm/snapshots/vmSnapshotsCard.jsx
  src/components/vm/snapshots/vmSnapshotsCard.scss
Labels: release-blocker

#264 package.json: Update @patternfly/react-console, @patternfly/react-core
  package.json
Labels: bot

#273 package.json: Update @patternfly/react-console, @patternfly/react-core
  package.json
Labels: bot

#277 [no-test] Update translations from Fedora Weblate
  po/nl.po
Labels: bot, no-test, release-blocker

#282 package.json: Update date-fns
  package.json
Labels: bot

#272 Disable non-shared storage migration for some distros
  src/components/vm/vmMigrateDialog.jsx
  src/components/vm/vmMigrateDialog.scss
  test/check-machines-migrate
Labels: release-blocker

#287 Bring back scrollbars in dialogs
  src/components/vm/vmMigrateDialog.scss
Labels: release-blocker
