Repository cockpit-project/cockpit-machines, pull requests merged in 2021-09, with the labels that each got.

#338 Fix crash when adding disk with custom path while no storage pools exist
  src/components/vm/disks/diskAdd.jsx
  test/check-machines-disks
Labels: release-blocker

#345 Some trivial Debian packaging updates
  packaging/debian/control
Labels: release-blocker

#341 Disable choosing write access when editing cdrom devices
  src/components/vm/disks/diskEdit.jsx
  test/check-machines-disks
Labels: release-blocker

#352 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#362 [no-test] Update translations from Fedora Weblate
  po/ko.po
Labels: bot, no-test, release-blocker

#365 Introduce rename operation
  src/components/vm/vmActions.jsx
  src/components/vm/vmRenameDialog.jsx
  src/libvirtApi/domain.js
  test/check-machines-lifecycle
Labels: release-note

#367 packit: Force dist download
  Makefile
  packit.yaml
Labels: no-test

#370 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#350 Stop providing options for shared memory when creating shared directories
  src/components/vm/filesystems/vmFilesystemsCard.jsx
  src/components/vm/vmDetailsPage.jsx
  src/libvirt-xml-create.js
  test/check-machines-filesystems
Labels: release-blocker

#373 [no-test] Update translations from Fedora Weblate
  po/ja.po
  po/zh_CN.po
Labels: bot, no-test, release-blocker

#380 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#390 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
Labels: bot, no-test, release-blocker

#402 [no-test] Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nb_NO.po
  po/nl.po
  po/pl.po
  po/ru.po
  po/sk.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
Labels: bot, no-test, release-blocker
