Repository cockpit-project/cockpit-machines, pull requests merged in 2021-05, with the labels that each got.

#125 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#158 Fix misalignment in the MAC address row in NIC edit dialog
  src/components/vm/nics/nicEdit.jsx
Labels: release-blocker

#15 Live migration
  src/components/vm/vmActions.jsx
  src/components/vm/vmMigrateDialog.jsx
  src/components/vm/vmMigrateDialog.scss
  src/libvirt-dbus.js
  test/check-machines-migrate
  test/storagelib.py
Labels: release-note

#159 Bump up cockpit tag for fetching test/common
  Makefile
  test/check-machines-lifecycle
Labels: release-blocker

#170 [no-test] Update translations from Fedora Weblate
  po/fr.po
Labels: bot, no-test, release-blocker

#175 package.json: Update @patternfly/react-styles, @patternfly/patternfly, @patternfly/react-core, @patternfly/react-table
  package.json
Labels: bot

#179 package.json: Update @patternfly/react-console
  package.json
Labels: bot

#183 fmf: Drop pillow test dependency
  test/browser/main.fmf
Labels: release-blocker
