Repository cockpit-project/cockpit-machines, pull requests merged in 2022-05, with the labels that each got.

#695 packit: Release to COPR
  .github/workflows/release.yml
  README.md
  cockpituous-release
  packit.yaml
Labels: no-test

#703 packit: Fix copr owner
  packit.yaml
Labels: no-test, release-blocker

#706 fmf: qemu-virtiofsd does not exist on RHEL 9
  test/browser/browser.sh
Labels: no-test, release-blocker

#711 test: Drop hack for Ubuntu 22.04
  test/vm.install
Labels: no-test

#715 Makefile: drop old comment
  Makefile
Labels: no-test

#716 packit: Use upstream tarball for release COPR build
  packit.yaml
Labels: release-blocker
