Repository cockpit-project/cockpit-machines, pull requests merged in 2023-05, with the labels that each got.

#1059 fmf: Put back virtiofsd on Rawhide
  packaging/cockpit-machines.spec.in
  test/browser/browser.sh
Labels: no-test, release-blocker

#1061 api: fetch domain state as last when re-fetching all domain propertie…
  src/libvirtApi/domain.js
Labels: release-blocker

#1065 Return a promise from networkGet and storagePoolGet functions
  src/libvirtApi/network.js
  src/libvirtApi/storagePool.js
Labels: release-blocker

#1068 Revert "fmf: Force nodejs 18 on Rawhide"
  test/browser/browser.sh
Labels: no-test

#986 Attach watchdog device only to offline XML if hotplug fails
  src/components/vm/overview/watchdog.jsx
  src/libvirtApi/domain.js
  test/check-machines-settings
Labels: release-note
