Repository cockpit-project/cockpit-machines, pull requests merged in 2023-02, with the labels that each got.

#943 .github: update release action workflow
  .github/workflows/release.yml
Labels: no-test

#950 Makefile: set TEST_OS to Fedora-37
  HACKING.md
  Makefile
Labels: no-test

#932 Hash passwords provided by the user for cloud base image
  src/libvirtApi/domain.js
Labels: needs-work

#949 packit: add Fedora 38 testing and release, drop Fedora 36
  packit.yaml
Labels: no-test

#960 spec: Work around spice bug in Fedora 38
  packaging/cockpit-machines.spec.in
Labels: release-blocker
