Repository cockpit-project/cockpit-machines, pull requests merged in 2024-01, with the labels that each got.

#1387 Add action to replace SPICE support
  src/components/common/needsShutdown.jsx
  src/components/vm/vmActions.jsx
  src/components/vm/vmReplaceSpiceDialog.jsx
  src/libvirt-xml-parse.js
  src/libvirt-xml-update.js
  src/libvirtApi/domain.js
  test/check-machines-create
Labels: release-note

#1410 .gitignore: improvements
  .gitignore
Labels: no-test

#1414 Show "Uses SPICE" warning on the overview
  src/components/vms/hostvmslist.jsx
  test/check-machines-create
Labels: release-blocker
