Repository cockpit-project/cockpit-machines, pull requests merged in 2025-06, with the labels that each got.

#2158 tests: change reference-image to fedora-42
  test/reference-image
Labels: no-test

#2150 nics: Allow managing source mode of directly attached network interfaces
  src/components/common/needsShutdown.tsx
  src/components/vm/nics/nicAdd.jsx
  src/components/vm/nics/nicBody.jsx
  src/components/vm/nics/nicEdit.jsx
  src/components/vm/nics/vmNicsCard.jsx
  src/libvirtApi/domain.ts
  test/check-machines-nics
Labels: release-note

#2171 nics: Replace text about direct mode with link to external docs
  src/components/vm/nics/nicBody.jsx
Labels: release-blocker
